# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://nunocoracao.github.io/blowfish/docs/getting-started/

theme = "blowfish"
defaultContentLanguage = "fr"

enableRobotsTXT = true
[pagination]
pagerSize = 100
summaryLength = 0

buildDrafts = false
buildFuture = false

enableEmoji = true

googleAnalytics = "G-T3BG1HKYZW"

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[caches]
[caches.images]
dir = ':cacheDir/images'
